# k8s/deployment.yaml -> redis 연결 추가 (AWS Cache v8)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: 051826731133.dkr.ecr.ap-northeast-2.amazonaws.com/cjone-dev:3f9e4f5
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cjone-dev-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cjone-dev-db-secret
                  key: DB_PASSWORD

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cjone-dev-redis
                  key: redis-password

            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: opensearch-credentials
                  key: username
                  
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-credentials
                  key: password
