# k8s/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app

          image: 051826731133.dkr.ecr.ap-northeast-2.amazonaws.com/cjone-dev:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cjone-dev-db-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cjone-dev-db-secret
                  key: DB_PASSWORD
